# status codes
SUCCESS_STATUS_CODE = 200
NO_CONTENT_STATUS_CODE = 204
BAD_REQUEST_STATUS_CODE = 400
FAIL_STATUS_CODE = 500
PARAMETER_VALIDATION = 1008
METHOD_NOT_ALLOWED_CODE = 405
INVALID_STATUS_CODE = 404
INVALID_INPUT_ERROR_CODE = 4001
WRONG_DATA_STATUS_CODE = 4002
DATA_UPTO_DATE = 4003
DUPLICATE_DATA = 4004
UNSUPPORTED_MEDIA_TYPE =415

# status
SUCCESS_STATUS = "SUCCESS"
FAIL_STATUS = "FAIL"

# messages
PARAMETER_MISSING_MESSAGE = 'Required Parameters Missing!'
PARAMETER_MISSING_OR_INVALID_MESSAGE = 'Required Parameters Missing or Invalid!'
INVALID_INPUT_ERROR_MESSAGE = "You have entered invalid data!"
