# Generated by Django 2.2.13 on 2020-06-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammatches',
            name='team_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_team', to='game.AmTeam'),
        ),
        migrations.AlterField(
            model_name='ammatches',
            name='team_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_team', to='game.AmTeam'),
        ),
        migrations.AlterField(
            model_name='ampoints',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_between', to='matches.AmMatches'),
        ),
        migrations.AlterField(
            model_name='ampoints',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='points_own', to='game.AmTeam'),
        ),
    ]
