# Generated by Django 2.2.13 on 2020-06-15 09:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('constant_type', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('is_editable', models.BooleanField(default=0)),
                ('is_visible', models.BooleanField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Constant',
                'verbose_name_plural': 'constant',
                'db_table': 'am_constants',
            },
        ),
        migrations.CreateModel(
            name='AmTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_digits=False, length=6, unique=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
                'db_table': 'am_team',
            },
        ),
        migrations.CreateModel(
            name='AmPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_digits=False, length=6, unique=True)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_matches', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('hieghest_score', models.IntegerField(blank=True, null=True)),
                ('fifties', models.IntegerField(blank=True, null=True)),
                ('hundreds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player', to='game.AmTeam')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Player',
                'db_table': 'am_player',
            },
        ),
    ]
